/*
 * Quality System TypeScript Interfaces
 *
 * These interfaces define the core types for the quality system
 * following Clean Architecture principles with no hardcoded paths.
 */

/**
 * Generic type for configuration and metrics values
 */
export type ConfigValue = string | number | boolean | object;

/**
 * Result of executing a quality gate or validation
 */
export interface QualityResult {
  success: boolean;
  executionTime: number;
  output?: string;
  error?: string;
  metrics?: Record<string, ConfigValue>;
}

/**
 * Execution context for quality operations
 */
export interface ExecutionContext {
  projectPath: string;
  files: string[];
  config?: Record<string, ConfigValue>;
}

/**
 * Base interface for all quality gates
 */
export interface QualityGate {
  name: string;
  critical: boolean;
  enabled: boolean;
  execute(context: ExecutionContext): Promise<QualityResult>;
}

/**
 * Validation check interface for pre-task validation
 */
export interface ValidationCheck {
  name: string;
  required: boolean;
  passed: boolean;
  message: string;
  details?: Record<string, ConfigValue>;
}

/**
 * Project configuration interface
 */
export interface ProjectConfig {
  name: string;
  version: string;
  paths: {
    src: string;
    test: string;
    config: string;
    root: string;
  };
  thresholds: {
    coverage: number;
    performance: number;
    complexity: number;
  };
}

/**
 * Performance metrics for quality monitoring
 */
export interface PerformanceMetrics {
  executionTime: number;
  memoryUsage: number;
  cpuUtilization: number;
}

/**
 * Quality trends analysis
 */
export interface QualityTrends {
  qualityScore: number;
  performanceScore: number;
  maintainabilityScore: number;
}

/**
 * Quality metrics interface for advanced analytics
 */
export interface QualityMetrics {
  timestamp: number;
  qualityScore: number;
  technicalDebt: 'LOW' | 'MEDIUM' | 'HIGH';
  performance: PerformanceMetrics;
  gates: {
    executionTime: number;
    successRate: number;
    failureRate: number;
  };
  trends: QualityTrends;
  eslintErrorRate: number;
  averageExecutionTime: number;
  gateExecutions: GateExecution[];
}

/**
 * Gate execution tracking
 */
export interface GateExecution {
  gateName: string;
  executionTime: number;
  success: boolean;
  timestamp: number;
}

/**
 * Recommendation for quality improvements
 */
export interface Recommendation {
  type: 'PERFORMANCE' | 'QUALITY' | 'SECURITY';
  priority: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
  description: string;
  action: string;
}

/**
 * Overall quality metrics
 */
export interface OverallQuality {
  qualityScore: number;
  technicalDebt: 'LOW' | 'MEDIUM' | 'HIGH';
  performance: PerformanceMetrics;
}

/**
 * Quality report generated by dashboard
 */
export interface QualityReport {
  timestamp: number;
  overall: OverallQuality;
  gates: {
    executionTime: number;
    successRate: number;
    failureRate: number;
  };
  trends: QualityTrends;
  recommendations: Recommendation[];
}

/**
 * Alert severity levels
 */
export type AlertSeverity = 'CRITICAL' | 'HIGH' | 'MEDIUM' | 'LOW' | 'INFO';

/**
 * Individual alert object
 */
export interface Alert {
  id: string;
  timestamp: number;
  severity: AlertSeverity;
  title: string;
  message: string;
  description: string;
  action: string;
}

/**
 * Input for creating new alerts
 */
export interface AlertInput {
  severity: AlertSeverity;
  title: string;
  message: string;
  action: string;
}

/**
 * Results from evaluating alerts based on metrics
 */
export interface AlertResults {
  critical: Alert[];
  warnings: Alert[];
  info: Alert[];
}
